name: Build and Release Python Binary

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**' # ymlが更新されたら動く
      - 'main.py'              # コードが更新されても動く

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Nuitka and dependencies
        run: |
          pip install "Nuitka[onefile]" zstandard

      - name: Build with Nuitka
        # --assume-yes-for-downloads でエラーを回避
        run: |
          python -m nuitka --onefile --standalone --assume-yes-for-downloads --output-filename=my_app.exe main.py

      - name: Create or Update Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "latest-build" # 特定のタグ名に固定して上書き
          files: my_app.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
