name: Release Binary

on:
  push:
    tags:
      - 'v*' # v1.0, v1.1 などのタグが打たれた時だけ動く

jobs:
  build:
    runs-on: windows-latest # Windows用exeを作る場合
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install Nuitka
        run: pip install nuitka

      - name: Build with Nuitka
        run: python -m nuitka --onefile --standalone main.py

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: main.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
